import Head from "next/head";
import Image from "next/image";

import { Footer } from "../components/footer";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Recycle Bicycle</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🚴‍♂️</text></svg>"
        />
      </Head>
      <div className="relative flex flex-col min-h-screen">
        <main className="flex flex-1">
          <Image
            src="/recycle-bicycle.jpg"
            alt=""
            className="fixed inset-0 object-cover w-full h-full"
            layout="fill"
          />
          <div className="relative flex-1 px-4 py-16 mx-auto text-center bg-black bg-opacity-75 max-w-7xl sm:px-6 sm:py-12 lg:px-8 lg:pt-48">
            <p className="flex items-center justify-center text-sm font-semibold tracking-wide text-white text-opacity-50 uppercase">
              Service
              <span className="inline-block w-0.5 opacity-50 h-3 mx-3 bg-white" />{" "}
              Sales{" "}
              <span className="inline-block w-0.5 opacity-50 h-3 mx-3 bg-white" />{" "}
              Spares{" "}
              <span className="inline-block w-0.5 opacity-50 h-3 mx-3 bg-white" />{" "}
              Repairs
            </p>
            <h1 className="mt-2 text-4xl font-extrabold tracking-tight text-white sm:text-5xl">
              Recycle Bicycle
            </h1>
            <div className="mt-4 space-y-2">
              <p className="text-lg font-medium text-white text-opacity-50">
                Port Macquarie NSW
              </p>
              <p className="text-lg font-medium text-white text-opacity-50">
                Any unwanted bikes needed, in any condition
              </p>
            </div>
            <div className="mt-6">
              <a
                href="tel:0413829314"
                className="inline-flex items-center px-4 py-2 text-sm font-medium text-white text-opacity-75 bg-white bg-opacity-25 border border-transparent rounded-md sm:hover:bg-opacity-50"
              >
                Call Cameron: 0413 829 314
              </a>
            </div>
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}
